[package]
name = "cluelessd3v/remotehub"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT OR Apache-2.0"
authors = ["Joaquin Von Chong/Clueless_Dev <cluelessdevmail@gmail.com>"]

[dependencies]
stew = "solarscuffle-bot/stew@1.0.8"
loader = "sleitnick/loader@2.0.0"
